# Generated by Django 5.2.8 on 2025-11-24 12:57

import e_health.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCustomFielModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('comma_separated_numbers', e_health.fields.CommaSeparatedCharField(max_length=255)),
            ],
            options={
                'db_table': 'test_custom_model',
            },
        ),
    ]
